#!/bin/bash


nuevo_usuario="bot"

# Verificar si el usuario ya existe
if id "$nuevo_usuario" &>/dev/null; then
    echo "El usuario ya existe."
else
    sudo adduser --disabled-password --gecos "" $nuevo_usuario
    chmod +x /usr/bin/bot.py
fi



pip3 install --upgrade python-telegram-bot
pip3 install python-nmap
echo " Restarting systemctl"

systemctl restart bot.service 


exit 0

