#!/usr/bin/python3

import sys
import os
import pwd

id = os.getuid()
usuario = os.getlogin()

if id > 1000:
    print ("--El usuario ["+usuario+"] es valido con id: "+str(id)+"\n")
else:
    print("--El usuario ["+usuario+"] es superusuario o principal con id "+str(id)+"\n")
    sys.exit(1)

info_usuario =  pwd.getpwnam(pwd.getpwuid(os.geteuid()).pw_name)
gecos = info_usuario[4]
carpeta = info_usuario[5]
ps1 = os.environ.get('PS1')

print ("--El GECOS del usuario "+str(usuario)+" es: "+str(gecos)+"\n")
print ("--La carpeta personal de "+str(usuario)+" es: "+str(carpeta)+"\n")

if ps1 is not None:
    print("--La variable de entorno $PS1 es :"+str(ps1))
else:
    print("[ERROR]-No tienes variable de entorno $PS1")
    sys.exit(1)


sys.exit(0)
