#!/usr/bin/python3

import sys
import netifaces


lista = str(netifaces.interfaces())

for interfaz in lista:
    print(interfaz)
    #info = netifaces.ifaddresses(lista)
    #print(info)










sys.exit(0)
